library(dplyr)
library(MTS)
library(ggplot2)
dane <- read.csv("dane.csv", header=T, sep=",")
dane$Date <- as.Date(dane$Date,"%d/%m/%Y")
BUMIX <- dane[dane$Name=="BUMIX",]
BUX <-dane[dane$Name=="BUX",]
CETOP <- dane[dane$Name=="CETOP",]
df0<-merge(BUX,BUMIX,by="Date")
df<-merge(df0,CETOP,by="Date")
df<-na.omit(df)

#stopy logarytmiczne

stoplog<-function(dane){
  wynik<-c(0)
  for(i in 1:(length(dane)-1)){
    
    stopa<-100*log(dane[i+1]/dane[i])
    wynik[i]<-stopa
  }
  
  return(wynik)
}

stopa.cetop<-stoplog(df$Close.price)
stopa.bux<-stoplog(df$Close.price.x)
stopa.bumix<-stoplog(df$Close.price.y)

dane1<-df[-1,]
dane1$stopa.cetop<-as.numeric(stopa.cetop)
dane1$stopa.bux<-as.numeric(stopa.bux)
dane1$stopa.bumix<-as.numeric(stopa.bumix)
dane1<-na.omit(dane1)
strata_bux<-data.frame(Data=dane1$Date,logreturn=-(dane1$stopa.bux))
strata_cetop<-data.frame(Data=dane1$Date,logreturn=-(dane1$stopa.cetop))
strata_bumix<-data.frame(Data=dane1$Date,logreturn=-(dane1$stopa.bumix))
strata_bux <- strata_bux %>% add_row()  
strata_bumix <- strata_bumix %>% add_row()
strata_cetop <- strata_cetop %>% add_row()


#deklaracja kolumn

strata_bux$var_99_250 <- NA
strata_bux$es_99_250 <- NA
strata_bux$var_95_250<- NA
strata_bux$es_95_250 <- NA
strata_bumix$var_99_250 <- NA
strata_bumix$es_99_250 <- NA
strata_bumix$var_95_250 <- NA
strata_bumix$es_95_250 <- NA
strata_cetop$var_99_250 <- NA
strata_cetop$es_99_250 <- NA
strata_cetop$var_95_250 <- NA
strata_cetop$es_95_250 <- NA
strata_bux$var_99_250_EWMA <- NA
strata_bux$es_99_250_EWMA <- NA
strata_bux$var_95_250_EWMA<- NA
strata_bux$es_95_250_EWMA <- NA
strata_bumix$var_99_250_EWMA <- NA
strata_bumix$es_99_250_EWMA <- NA
strata_bumix$var_95_250_EWMA<- NA
strata_bumix$es_95_250_EWMA <- NA
strata_cetop$var_99_250_EWMA <- NA
strata_cetop$es_99_250_EWMA <- NA
strata_cetop$var_95_250_EWMA <- NA
strata_cetop$es_95_250_EWMA <- NA
strata_bux$var_99_250_mc <- NA
strata_bux$es_99_250_mc <- NA
strata_bux$var_95_250_mc<- NA
strata_bux$es_95_250_mc <- NA
strata_bumix$var_99_250_mc <- NA
strata_bumix$es_99_250_mc <- NA
strata_bumix$var_95_250_mc<- NA
strata_bumix$es_95_250_mc <- NA
strata_cetop$var_99_250_mc <- NA
strata_cetop$es_99_250_mc <- NA
strata_cetop$var_95_250_mc <- NA
strata_cetop$es_95_250_mc <- NA
strata_bux$test1 <- NA
strata_bux$test2 <- NA
strata_bux$test3 <- NA
strata_bumix$test1 <- NA
strata_bumix$test2 <- NA
strata_bumix$test3 <- NA
strata_cetop$test1 <- NA
strata_cetop$test2 <- NA
strata_cetop$test3 <- NA


#metoda historyczna

for (i in seq(1,nrow(strata_bux)-250,1)){
  probka <- strata_bux[i:(249+i),]
  kwantyl_99 <- quantile(probka$logreturn, 0.99, na.rm = T)
  kwantyl_95 <- quantile(probka$logreturn, 0.95, na.rm = T)
  strata_bux$var_99_250[250+i] <- kwantyl_99
  strata_bux$var_95_250[250+i] <- kwantyl_95
  probka_99 <- probka %>% filter(logreturn > kwantyl_99)
  w_99 = mean(probka_99$logreturn)
  strata_bux$es_99_250[250+i] <- w_99
  probka_95 <- probka %>% filter(logreturn > kwantyl_95)
  w_95 = mean(probka_95$logreturn)
  strata_bux$es_95_250[250+i] <- w_95
}

for (i in seq(1,nrow(strata_bumix)-250,1)){
  probka <- strata_bumix[i:(249+i),]
  kwantyl_99 <- quantile(probka$logreturn, 0.99, na.rm = T)
  kwantyl_95 <- quantile(probka$logreturn, 0.95, na.rm = T)
  strata_bumix$var_99_250[250+i] <- kwantyl_99
  strata_bumix$var_95_250[250+i] <- kwantyl_95
  probka_99 <- probka %>% filter(logreturn > kwantyl_99)
  w_99 = mean(probka_99$logreturn)
  strata_bumix$es_99_250[250+i] <- w_99
  probka_95 <- probka %>% filter(logreturn > kwantyl_95)
  w_95 = mean(probka_95$logreturn)
  strata_bumix$es_95_250[250+i] <- w_95
}

for (i in seq(1,nrow(strata_cetop)-250,1)){
  probka <- strata_cetop[i:(249+i),]
  kwantyl_99 <- quantile(probka$logreturn, 0.99, na.rm = T)
  kwantyl_95 <- quantile(probka$logreturn, 0.95, na.rm = T)
  strata_cetop$var_99_250[250+i] <- kwantyl_99
  strata_cetop$var_95_250[250+i] <- kwantyl_95
  probka_99 <- probka %>% filter(logreturn > kwantyl_99)
  w_99 = mean(probka_99$logreturn)
  strata_cetop$es_99_250[250+i] <- w_99
  probka_95 <- probka %>% filter(logreturn > kwantyl_95)
  w_95 = mean(probka_95$logreturn)
  strata_cetop$es_95_250[250+i] <- w_95
}


# EWMA

for (i in seq(1,nrow(strata_bux)-250,1)){
  probka <- strata_bux[i:(249+i),]
  probka$vol<-EWMAvol(probka$logreturn, lambda=0.999)$Sigma.t
  probka<-probka %>% mutate(Z = logreturn * lead(vol)/vol)
  kwantyl_99<-quantile(probka$Z, .99, na.rm = T)
  kwantyl_95<-quantile(probka$Z, .95, na.rm=T)
  strata_bux$var_99_250_EWMA[250+i] <- kwantyl_99
  strata_bux$var_95_250_EWMA[250+i] <- kwantyl_95
  probka2 <- probka %>% filter(Z > kwantyl_99)
  w_99 = mean(probka2$Z)
  strata_bux$es_99_250_EWMA[250+i] <- w_99
  probka3 <- probka %>% filter(Z > kwantyl_95)
  w_95 = mean(probka3$Z)
  strata_bux$es_95_250_EWMA[250+i] <- w_95
}

for (i in seq(1,nrow(strata_bumix)-250,1)){
  probka <- strata_bumix[i:(249+i),]
  probka$vol<-EWMAvol(probka$logreturn, lambda=0.999)$Sigma.t
  probka<-probka %>% mutate(Z = logreturn * lead(vol)/vol)
  kwantyl_99<-quantile(probka$Z, .99, na.rm = T)
  kwantyl_95<-quantile(probka$Z, .95, na.rm=T)
  strata_bumix$var_99_250_EWMA[250+i] <- kwantyl_99
  strata_bumix$var_95_250_EWMA[250+i] <- kwantyl_95
  probka2 <- probka %>% filter(Z > kwantyl_99)
  w_99 = mean(probka2$Z)
  strata_bumix$es_99_250_EWMA[250+i] <- w_99
  probka3 <- probka %>% filter(Z > kwantyl_95)
  w_95 = mean(probka3$Z)
  strata_bumix$es_95_250_EWMA[250+i] <- w_95
}

for (i in seq(1,nrow(strata_cetop)-250,1)){
  probka <- strata_cetop[i:(249+i),]
  probka$vol<-EWMAvol(probka$logreturn, lambda=0.999)$Sigma.t
  probka<-probka %>% mutate(Z = logreturn * lead(vol)/vol)
  kwantyl_99<-quantile(probka$Z, .99, na.rm = T)
  kwantyl_95<-quantile(probka$Z, .95, na.rm= T)
  strata_cetop$var_99_250_EWMA[250+i] <- kwantyl_99
  strata_cetop$var_95_250_EWMA[250+i] <- kwantyl_95
  probka2 <- probka %>% filter(Z > kwantyl_99)
  w_99 = mean(probka2$Z)
  strata_cetop$es_99_250_EWMA[250+i] <- w_99
  probka3 <- probka %>% filter(Z > kwantyl_95)
  w_95 = mean(probka3$Z)
  strata_cetop$es_95_250_EWMA[250+i] <- w_95
}


# Monte Carlo

for (i in seq(1,nrow(strata_bux)-250,1)){
  probka <- strata_bux[i:(249+i),]
  m = mean(probka$logreturn)
  sd = sd(probka$logreturn)
  mcarlo <- rnorm(1000,mean=m, sd=sd)
  mcarlo      <- sort(mcarlo)                 
  M0          <- floor(1000*0.95)
  M1 <- floor(1000*0.99)                                
  var_95   <- mcarlo[M0]                  
  es_95     <- mean(mcarlo[1:M0])  
  var_99 <-mcarlo[M1]
  es_99 <-mean(mcarlo[1:M1])
  strata_bux$var_99_250_mc[250+i] <- var_99
  strata_bux$var_95_250_mc[250+i] <- var_95
  strata_bux$es_99_250_mc[250+i] <- es_99
  strata_bux$es_95_250_mc[250+i] <- es_95
}

for (i in seq(1,nrow(strata_bumix)-250,1)){
  probka <- strata_bumix[i:(249+i),]
  m = mean(probka$logreturn)
  sd = sd(probka$logreturn)
  mcarlo <- rnorm(1000,mean=m, sd=sd)
  mcarlo      <- sort(mcarlo)                 
  M0          <- floor(1000*0.95)
  M1 <- floor(1000*0.99)                                
  var_95   <- mcarlo[M0]                  
  es_95     <- mean(mcarlo[1:M0])  
  var_99 <-mcarlo[M1]
  es_99 <-mean(mcarlo[1:M1])
  strata_bumix$var_99_250_mc[250+i] <- var_99
  strata_bumix$var_95_250_mc[250+i] <- var_95
  strata_bumix$es_99_250_mc[250+i] <- es_99
  strata_bumix$es_95_250_mc[250+i] <- es_95
}

for (i in seq(1,nrow(strata_cetop)-250,1)){
  probka <- strata_cetop[i:(249+i),]
  m = mean(probka$logreturn)
  sd = sd(probka$logreturn)
  mcarlo <- rnorm(1:1000,mean=m, sd=sd)
  mcarlo      <- sort(mcarlo)                 
  M0          <- floor(1000*0.95)
  M1 <- floor(1000*0.99)                                
  var_95   <- mcarlo[M0]                  
  es_95     <- mean(mcarlo[1:M0])  
  var_99 <-mcarlo[M1]
  es_99 <-mean(mcarlo[1:M1])
  strata_cetop$var_99_250_mc[250+i] <- var_99
  strata_cetop$var_95_250_mc[250+i] <- var_95
  strata_cetop$es_99_250_mc[250+i] <- es_99
  strata_cetop$es_95_250_mc[250+i] <- es_95
}


#sprawdzanie wyjątków

for (i in seq(251,3983,1)) {
  if (-strata_bux$logreturn[i]>strata_bux$var_99_250[i])
  {strata_bux$test1[i]=strata_bux$logreturn[i]}
  else {strata_bux$test1[i]=0}
  
  if (-strata_bux$logreturn[i]>strata_bux$var_99_250_EWMA[i])
  {strata_bux$test2[i]=strata_bux$logreturn[i]}
  else {strata_bux$test2[i]=0}
  
  if (-strata_bux$logreturn[i]>strata_bux$var_99_250_mc[i])
  {strata_bux$test3[i]=strata_bux$logreturn[i]}
  else {strata_bux$test3[i]=0}
}

for (i in seq(251,3983,1)) {
  if (-strata_bumix$logreturn[i]>strata_bumix$var_99_250[i])
  {strata_bumix$test1[i]=strata_bumix$logreturn[i]}
  else {strata_bumix$test1[i]=0}
  
  if (-strata_bumix$logreturn[i]>strata_bumix$var_99_250_EWMA[i])
  {strata_bumix$test2[i]=strata_bumix$logreturn[i]}
  else {strata_bumix$test2[i]=0}
  
  if (-strata_bumix$logreturn[i]>strata_bumix$var_99_250_mc[i])
  {strata_bumix$test3[i]=strata_bumix$logreturn[i]}
  else {strata_bumix$test3[i]=0}
}

for (i in seq(251,3983,1)) {
  if (-strata_cetop$logreturn[i]>strata_cetop$var_99_250[i])
  {strata_cetop$test1[i]=strata_cetop$logreturn[i]}
  else {strata_cetop$test1[i]=0}
  
  if (-strata_cetop$logreturn[i]>strata_cetop$var_99_250_EWMA[i])
  {strata_cetop$test2[i]=strata_cetop$logreturn[i]}
  else {strata_cetop$test2[i]=0}
  
  if (-strata_cetop$logreturn[i]>strata_cetop$var_99_250_mc[i])
  {strata_cetop$test3[i]=strata_cetop$logreturn[i]}
  else {strata_cetop$test3[i]=0}
}

df_bux <- na.omit(strata_bux[251:(nrow(strata_bux)),])
df_cetop <- na.omit(strata_cetop[251:(nrow(strata_cetop)),])
df_bumix <- na.omit(strata_bumix[251:(nrow(strata_bumix)),])

#testy dla 99% pewności

kupiec <- function(excepts){
  n=length(excepts)-1
  m=sum(excepts!=0)
  wartosc=2*log((1-m/n)^(n-m)*(m/n)^m)-2*log((1-0.01)^(n-m)*0.01^m)  
  p <- 1-pchisq(q=wartosc, df=1)
  statystyki <- data.frame(wartosc,p)
  return(statystyki)
}

christof <- function(excepts){
  n00=0
  n01=0
  n10=0
  n11=0
  for(i in seq(length(excepts)-2)){
    if(excepts[i] ==0){
      if(excepts[i+1] ==0) {n00=n00+1}
      else {n01=n01+1}
    }
    
    if(excepts[i] !=0){
      if(excepts[i+1] ==0) {n10=n10+1}
      else {n11=n11+1}
    }
  }
  
  pi01=n01/(n00+n01)
  pi11=n11/(n10+n11)
  pi=(n01+n11) /(n00+n01+n10+n11)
  wartosc=2*log  ((1-pi01)^(n00) *pi01^n01*(1-pi11)^(n10) *pi11^n11) -2*log((1-pi)^(n00+n10) *pi^(n01+n11))
  p <- 1-pchisq(q=wartosc, df=1)
  statystyki <- data.frame(wartosc,p)
  return(statystyki)
}

test_bux <- rbind(kupiec(df_bux$test1),christof(df_bux$test1),
                  kupiec(df_bux$test2),christof(df_bux$test2),
                  kupiec(df_bux$test3),christof(df_bux$test3),
                  deparse.level=4)
test_bumix <- rbind(kupiec(df_bumix$test1),christof(df_bumix$test1),
                    kupiec(df_bumix$test2),christof(df_bumix$test2),
                    kupiec(df_bumix$test3),christof(df_bumix$test3),
                    deparse.level=4)
test_cetop <- rbind(kupiec(df_cetop$test1),christof(df_cetop$test1),
                    kupiec(df_cetop$test2),christof(df_cetop$test2),
                    kupiec(df_cetop$test3),christof(df_cetop$test3),
                    deparse.level=4)


